spring.application.name=bff-agendador-tarefas

usuario.url=localhost:8080/usuario

usuario.email=admin@admin.com

usuario.senha=12345

tarefa.url=localhost:8081/tarefas

notificacao.url=localhost:8082/email

server.port=8083

cron.horario=0 0/5 * * * ?

